server:
  port: 8086

spring:
  application:
    name: schedulerService
  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

